name: Dev Release

on:
  push:
    tags: [ "rhone+*" ]

jobs:
  buildx_and_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Get the version
        id: get_version
        run: |
          version=$(git describe --tags --abbrev=0)
          echo $version
          echo ::set-output name=VERSION::$version
        shell: bash

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Assemble the Jar file
        id: get_jar
        run: |
          make assembly && cp app/target/scala-2.13/alephium-*.jar docker/release/
          jar=$(cd docker/release && ls alephium-*.jar)
          echo $jar
          echo ::set-output name=ALEPHIUM_JAR::$jar
        shell: bash

      - name: Build and publish full node docker image for stable versions
        uses: docker/build-push-action@v2
        with:
          context: docker/release
          file: ./docker/release/Dockerfile.dev
          build-args: |
            RELEASE=${{ steps.get_version.outputs.VERSION }}
            ALEPHIUM_JAR=${{ steps.get_jar.outputs.ALEPHIUM_JAR }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            docker.io/alephium/dev-alephium:${{ steps.get_version.outputs.VERSION }}
          push: true
